package com.petech.thomasgregchallenge.ui.register.viewmodel;

public enum RegisterUserError {
    DATA_FIELD_EMPTY,
    USER_DETAILS_EMPTY,
    USER_DOCUMENT_EMPTY,
    USER_PASSWORD_EMPTY,
    NAME_MUST_BE_COMPLETE,
    EMAIL_INVALID,
    USER_NAME_ALREADY_EXISTS,
    UNKNOWN_ERROR,
    USER_UNDER_AGE,
    INVALID_CPF,
    INVALID_CNPJ,
    INVALID_PASSWORD,
    PASSWORD_DONT_MATCHES,
    REGISTRATION_ERROR
}
